CREATE TABLE IF NOT EXISTS `destinations` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY,
  `name_es` VARCHAR(150) NOT NULL,
  `name_en` VARCHAR(150) NOT NULL,
  `desc_es` TEXT,
  `desc_en` TEXT,
  `tag_es` VARCHAR(150),
  `tag_en` VARCHAR(150),
  `image` LONGTEXT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
